#file: noinspection YAMLSchemaValidation
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys EventBridge resources

Parameters:
  EnvironmentName:
    Type: String

Resources:
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub ${EnvironmentName}-event-bus

  EventSchemasDiscoverer:
    Type: AWS::EventSchemas::Discoverer
    Properties:
      CrossAccount: true
      Description: !Sub ${EnvironmentName}-event-bus schema discoverer
      SourceArn: !GetAtt EventBus.Arn

Outputs:
  EventBus:
    Description: Name of event bus
    Value: !Ref EventBus
    Export:
      Name: !Sub ${EnvironmentName}:EventBus