#file: noinspection YAMLSchemaValidation
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys Event Bridge resources

Parameters:
  EnvironmentName:
    Type: String

Resources:

  SchemaRegistry:
    Type: AWS::EventSchemas::Registry
    Properties:
      RegistryName: !Sub ${EnvironmentName}-schema-registry
      Description: !Sub ${EnvironmentName} schema registry

  MySchema:
    Type: AWS::EventSchemas::Schema
    Properties:
      RegistryName: !Ref SchemaRegistry
      Type: OpenApi3
      Description: My Event Schema
      Content: |
        {
          "openapi": "3.0.0",
          "info": {
            "title": "Rewards Schema",
            "version": "1.0"
          },
          "paths": {
          },
          "components": {
            "schemas": {
              "Reward": {
                "type": "object",
                "properties": {
                  "uuid": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "required": [
                  "uuid",
                  "name"
                ]
              }
            }
          }
        }