AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys Event Bridge resources

Parameters:
  EnvironmentName:
    Type: String

Resources:

  SchemaRegistry:
    Type: AWS::EventSchemas::Registry
    Properties:
      RegistryName: !Sub ${EnvironmentName}-schema-registry
      Description: !Sub ${EnvironmentName} schema registry