AWSTemplateFormatVersion: 2010-09-09
Description: Open Search serverless collections

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcPrivateSubnetIds:
    Type: CommaDelimitedList

Resources:

  OpenSearchUser:
    Type: AWS::IAM::User
    Properties:
      UserName: open-search-user

  OpenSearchUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref OpenSearchUser
      Serial: 1

  DataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-ap
      Type: data
      Description: !Sub ${EnvironmentName} access policy
      Policy: !Sub >-
        [
          {
            "Rules": [
              {
                "ResourceType": "index",
                "Resource": [
                  "index/*/*"
                ],
                "Permission": [
                  "aoss:*"
                ]
              },
              {
                "Resource": [
                  "collection/${EnvironmentName}*"
                ],
                "Permission": [
                  "aoss:*"
                ],
                "ResourceType": "collection"
              }
            ],
            "Principal": [
              "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/observability.aoss.amazonaws.com/AWSServiceRoleForAmazonOpenSearchServerless",
              "${OpenSearchUser.Arn}"
            ]
          }
        ]

  NetworkSecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    DependsOn: VpcEndpoint
    Properties:
      Name: !Sub ${EnvironmentName}-nsp
      Type: network
      Description: !Sub ${EnvironmentName} network security policy
      Policy: !Sub >-
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": [
                  "collection/${EnvironmentName}*"
                ]
              },
              {
                "ResourceType": "dashboard",
                "Resource": [
                  "collection/${EnvironmentName}*"
                ]
              }
            ],
            "AllowFromPublic": false,
            "SourceVPCEs": [
              "${VpcEndpoint}"
            ]
          }
        ]

  EncryptionSecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-esp
      Type: encryption
      Description: !Sub ${EnvironmentName} encryption security policy
      Policy: !Sub >-
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": [
                "collection/${EnvironmentName}*"
              ]
            }
          ],
          "AWSOwnedKey": true
        }

  VpcEndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-vpc-endpoint-sg
      GroupDescription: OpenSearch Serverless VPC endpoint security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  VpcEndpoint:
    Type: AWS::OpenSearchServerless::VpcEndpoint
    Properties:
      Name: !Sub ${EnvironmentName}-vpc-endpoint
      VpcId: !Ref VpcId
      SubnetIds: !Ref VpcPrivateSubnetIds
      SecurityGroupIds: [ !Ref VpcEndpointSG ]

  RewardsCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn:
      - NetworkSecurityPolicy
      - EncryptionSecurityPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-rewards
      Type: SEARCH
      Description: Reward service collection

Outputs:
  RewardsCollectionDashboardURL:
    Value: !GetAtt RewardsCollection.DashboardEndpoint
  RewardsCollectionArn:
    Value: !GetAtt RewardsCollection.Arn