AWSTemplateFormatVersion: 2010-09-09
Description: Open search serverless collections

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcPrivateSubnetIds:
    Type: CommaDelimitedList

Resources:

  RewardsCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn: EncryptionPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-rewards
      Type: SEARCH
      Description: Search reward service collection

  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub collection/${EnvironmentName}-* security policy
      Type: encryption
      Description: Encryption policy for test collection
      Policy: >-
        !Sub {"Rules":[{"ResourceType":"collection","Resource":["collection/${EnvironmentName}-*"]}],"AWSOwnedKey":true}