AWSTemplateFormatVersion: 2010-09-09
Description: Open search serverless collections

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcPrivateSubnetIds:
    Type: CommaDelimitedList

Resources:

  SecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-sp
      Type: encryption
      Description: !Sub collection/${EnvironmentName}-* security policy
      Policy: !Sub >-
        {"Rules":[{"ResourceType":"collection","Resource":["collection/${EnvironmentName}-*"]}],"AWSOwnedKey":true}

  RewardsCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn: SecurityPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-rewards
      Type: SEARCH
      Description: Search reward service collection

Outputs:
  RewardsCollectionDashboardURL:
    Value: !GetAtt RewardsCollection.DashboardEndpoint
  RewardsCollectionArn:
    Value: !GetAtt RewardsCollection.Arn