AWSTemplateFormatVersion: 2010-09-09
Description: Open search serverless collections

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcPrivateSubnetIds:
    Type: CommaDelimitedList

Resources:

  SecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-sp
      Type: encryption
      Description: !Sub collection/${EnvironmentName}-* security policy
      Policy: !Sub >-
        {"Rules":[{"ResourceType":"collection","Resource":["collection/${EnvironmentName}-*"]}],"AWSOwnedKey":true}

  VpcEndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-vpc-endpoint-sg
      GroupDescription: OpenSearch Serverless VPC endpoint security group
      VpcId: !Ref VpcId

  VpcEndpoint:
    Type: AWS::OpenSearchServerless::VpcEndpoint
    Properties:
      Name: !Sub ${EnvironmentName}-vpc-endpoint
      VpcId: !Ref VpcId
      SubnetIds: !Ref VpcPrivateSubnetIds
      SecurityGroupIds: [ !Ref VpcEndpointSG ]

  RewardsCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn: SecurityPolicy
    Properties:
      Name: !Sub ${EnvironmentName}-rewards
      Type: SEARCH
      Description: Search reward service collection

Outputs:
  RewardsCollectionDashboardURL:
    Value: !GetAtt RewardsCollection.DashboardEndpoint
  RewardsCollectionArn:
    Value: !GetAtt RewardsCollection.Arn