AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys Postgres DB

Parameters:
  EnvironmentName:
    Type: String
  DBName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcPrivateSubnetIds:
    Type: CommaDelimitedList

Resources:

  DatabaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: access-rds-sg
      GroupDescription: Open database for access
      VpcId: !Ref VpcId

  DBVpcSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${EnvironmentName}-db-vpc-subnet-group
      DBSubnetGroupDescription: DB subnet group to connect in private vpc
      SubnetIds: !Ref VpcPrivateSubnetIds

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: 14.7
      MultiAZ: false
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref RDSSecrets, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref RDSSecrets, ':SecretString:password}}' ] ]
      DBSubnetGroupName: !Ref DBVpcSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DatabaseSG.GroupId

  RDSSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/rds
      Description: "Access keys to Postgres DB. This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "master"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludePunctuation: true

  #This is a SecretTargetAttachment resource which updates the referenced Secret resource with properties about
  #the referenced RDS instance
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref RDSSecrets
      TargetId: !Ref DBInstance
      TargetType: AWS::RDS::DBInstance

Outputs:
  DBInstance:
    Description: The DB instance ID
    Value: !Ref DBInstance
    Export:
      Name: !Sub ${EnvironmentName}:DBInstance
  DBName:
    Description: The DB instance host
    Value: !Ref DBName
    Export:
      Name: !Sub ${EnvironmentName}:DBName
  DBInstanceHost:
    Description: The DB instance host
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}:DBInstanceHost
  DBInstancePort:
    Description: The DB instance port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${EnvironmentName}:DBInstancePort
  DatabaseSG:
    Description: The DB security group
    Value: !Ref DatabaseSG
    Export:
      Name: !Sub ${EnvironmentName}:DatabaseSG
  RDSSecretsArn:
    Description: RDS Secrets ARN
    Value: !Ref RDSSecrets
    Export:
      Name: !Sub ${EnvironmentName}:RDSSecrets
