AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys AWS Utility resources

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id

Resources:

  EC2UtilInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EC2 instance
      VpcId: !Ref VpcId

  EC2UtilInstanceIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      GroupId: !Ref EC2UtilInstanceSG
      CidrIp: 0.0.0.0/0

  EC2UtilInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2UtilRole

  EC2UtilRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2UtilRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'

  EC2UtilInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06ca3ca175f37dd66
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref EC2UtilInstanceSG
      IamInstanceProfile: !Ref EC2UtilInstanceProfile
