AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys AWS App Mesh

Parameters:
  EnvironmentName:
    Type: String
  AppDomainName:
    Type: String
  HostedZoneId:
    Type: String

Resources:

  ApplicationDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub ${EnvironmentName}.${AppDomainName}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub ${AppDomainName}
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub ${EnvironmentName}.${AppDomainName}
          HostedZoneId: !Ref HostedZoneId

Outputs:
  ApplicationDomainCertificateArn:
    Description: The application domain certificate arn
    Value: !Ref ApplicationDomainCertificate