AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys AWS SSl/TLS Certificates

Parameters:
  EnvironmentName:
    Type: String
  AppDomainName:
    Type: String
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id

Resources:

  ApplicationCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref AppDomainName
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub '*.${AppDomainName}'
        - !Sub '*.*.${AppDomainName}'
      DomainValidationOptions:
        - DomainName: !Ref AppDomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  ApplicationCertificateArn:
    Description: The application domain certificate arn
    Value: !Ref ApplicationCertificate