AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates the infrastructure to host and expose a Single Page Application:
      - An Amazon S3 bucket for hosting the application
      - An Amazon CloudFront distribution to expose the application
      - An Amazon S3 bucket for hosting bucket and cloudfront access logs
      - A public API to be used by the application to demonstrate CORS configuration

Parameters:
  EnvironmentName:
    Type: String

Resources:

  # The Amazon S3 bucket into which Client Application build files must be deployed
  ClientAppS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${EnvironmentName}-client-app'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref ClientAppLogsS3Bucket
        LogFilePrefix: s3-access-logs
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  # The Amazon S3 bucket policy for securing the bucket hosting the application
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ClientAppS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PolicyForCloudFrontPrivateContent
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CFOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject*'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ClientAppS3Bucket
                - /*
      Bucket: !Ref ClientAppS3Bucket

  # The Amazon S3 bucket into which access logs from S3 (for the application) and CloudFront will be put
  # This bucket is private and only for storing logs
  ClientAppLogsS3Bucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - ClientAppS3Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ClientAppS3Bucket}-logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  # The Amazon CloudFront distribution exposing our Single Page Application
  # For demo purposes and to reduce cost, no WAF is configured
  CFDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - CFOriginAccessIdentity
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt ClientAppS3Bucket.RegionalDomainName
            Id: clientAppS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CFOriginAccessIdentity}"
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: clientAppS3Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        Logging:
          Bucket: !GetAtt ClientAppLogsS3Bucket.RegionalDomainName
          Prefix: 'cloudfront-access-logs'

  # The Amazon CloudFront origin access identity
  CFOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    DependsOn:
      - ClientAppS3Bucket
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub '${ClientAppS3Bucket}-origin-access-identity'

Outputs:
  ClientAppS3Bucket:
    Description: Name of client app s3 bucket
    Value: !Ref ClientAppS3Bucket
    Export:
      Name: !Sub ${EnvironmentName}:ClientAppS3Bucket