AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys AWS App Mesh

Parameters:
  EnvironmentName:
    Type: String

Resources:

  AppMesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Sub ${EnvironmentName}-app-mesh
      Spec:
        EgressFilter:
          Type: ALLOW_ALL
        ServiceDiscovery:
          IpPreference: IPv4_PREFERRED

Outputs:
  AppMeshArn:
    Description: The app mesh name
    Value: !Ref AppMesh
    Export:
      Name: !Sub ${EnvironmentName}:AppMeshArn
  AppMeshName:
    Description: The app mesh name
    Value: !GetAtt AppMesh.MeshName
    Export:
      Name: !Sub ${EnvironmentName}:AppMeshName