AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates the infrastructure to host and expose a Single Page Application:
      - An Amazon S3 bucket for hosting the application
      - An Amazon CloudFront distribution to expose the application
      - An Amazon S3 bucket for hosting bucket and cloudfront access logs
      - A public API to be used by the application to demonstrate CORS configuration

Parameters:
  EnvironmentName:
    Type: String
  ALBDNSName:
    Type: String

Resources:

  # The Amazon CloudFront distribution exposing our Single Page Application
  # For demo purposes and to reduce cost, no WAF is configured
  CFDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - CFOriginAccessIdentity
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !ImportValue
              'Fn::Sub': '${EnvironmentName}:ClientAppS3BucketRegionalDomainName'
            Id: clientAppS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CFOriginAccessIdentity}
#          - DomainName: !Ref ALBDNSName
#            Id: loadBalancerOrigin
#            CustomOriginConfig:
#              OriginProtocolPolicy: https-only
#              OriginSSLProtocols:
#                - TLSv1.2
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: clientAppS3Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        Logging:
          Bucket: !ImportValue
            'Fn::Sub': '${EnvironmentName}:ClientAppLogsS3BucketRegionalDomainName'
          Prefix: 'cloudfront-access-logs'

  # The Amazon CloudFront origin access identity
  CFOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${EnvironmentName}-client-app-origin-access-identity

  # The Amazon S3 bucket policy for securing the bucket hosting the application
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ClientAppS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PolicyForCloudFrontPrivateContent
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CFOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject*'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !ImportValue
                  'Fn::Sub': '${EnvironmentName}:ClientAppS3Bucket'
                - /*
      Bucket: !ImportValue
        'Fn::Sub': '${EnvironmentName}:ClientAppS3Bucket'