AWSTemplateFormatVersion: '2010-09-09'
Description: External, public facing load balancer, for forwarding public traffic to containers
Parameters:
  EnvironmentName:
    Type: String
    Default: ecs-course
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-poc-cluster

  ContainerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: container-sg
      GroupDescription: Access to the ECS hosts that run containers
      VpcId: !ImportValue
        'Fn::Sub': '${EnvironmentName}:VpcId'

  ContainerSGALBInboundRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt ContainerSG.GroupId
      IpProtocol: TCP
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !GetAtt PublicLoadBalancerSG.GroupId

  ContainerSGALBOutboundRule:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: !GetAtt ContainerSG.GroupId
      IpProtocol: TCP
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0

  PublicLoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: public-load-balancer-sg
      GroupDescription: Access to the public facing load balancer
      VpcId: !ImportValue
        'Fn::Sub': '${EnvironmentName}:VpcId'

  PublicLoadBalancerSGInboundRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt PublicLoadBalancerSG.GroupId
      IpProtocol: TCP
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0

  PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
      Subnets:
        - !ImportValue
          'Fn::Sub': '${EnvironmentName}:PublicSubnet1'
        - !ImportValue
          'Fn::Sub': '${EnvironmentName}:PublicSubnet2'
      SecurityGroups: [ !Ref 'PublicLoadBalancerSG' ]

  PublicLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - PublicLoadBalancer
    Properties:
      DefaultActions:
        - Type: 'redirect'
          RedirectConfig:
            Protocol: "#{protocol}"
            Port: "#{port}"
            Host: "#{host}"
            Path: "/default/"
            Query: "#{query}"
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref PublicLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  ExternalUrl:
    Description: The url of the external load balancer
    Value: !Sub http://${PublicLoadBalancer.DNSName}
    Export:
      Name: !Sub ${EnvironmentName}:ExternalUrl
  ECSCluster:
    Description: The ECS Cluster ID
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${EnvironmentName}:ECSCluster
  ContainerSG:
    Description: The Container Security Group ID
    Value: !Ref ContainerSG
    Export:
      Name: !Sub ${EnvironmentName}:ContainerSG
  PublicLoadBalancerListener:
    Description: The Container Security Group ID
    Value: !Ref PublicLoadBalancerListener
    Export:
      Name: !Sub ${EnvironmentName}:PublicLoadBalancerListener