Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  # ECS Resources
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}:poc-cluster


  # A security group for the containers we will run in Fargate.
  # Rules are added to this security group based on what ingress you
  # add for the cluster.
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the Fargate containers
      VpcId: !ImportValue
        'Fn::Sub': '${EnvironmentName}:VpcId'

Outputs:
  ContainerSecurityGroup:
    Description: A reference to Container Security Group
    Value: !Ref ContainerSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}:ContainerSecurityGroupId'