Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  # ECS Resources
  ECSCluster:
    Name: !Sub ${EnvironmentName}-poc-cluster
    Type: AWS::ECS::Cluster


  # A security group for the containers we will run in Fargate.
  # Rules are added to this security group based on what ingress you
  # add for the cluster.
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the Fargate containers
      VpcId: !ImportValue
        'Fn::Sub': '${EnvironmentName}-VPC'
