AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  StackTimeout:
    Default: 10
    Description: A stack timeout in minutes
    Type: String

Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ./vpc.yaml
      TimeoutInMinutes: !Ref StackTimeout

  #  S3:
  #    Type: AWS::CloudFormation::Stack
  #    Properties:
  #      Parameters:
  #        EnvironmentName: !Ref EnvironmentName
  #      Tags:
  #        - Key: environment
  #          Value: !Ref EnvironmentName
  #      TemplateURL: ./s3.yaml
  #      TimeoutInMinutes: !Ref StackTimeout

  ECSRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ./ecs-roles.yaml
      TimeoutInMinutes: !Ref StackTimeout

  RDS:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcSubnetIds:
          - !GetAtt [ VPC, Outputs.PrivateSubnet1 ]
          - !GetAtt [ VPC, Outputs.PrivateSubnet2 ]
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ./rds.yaml
      TimeoutInMinutes: !Ref StackTimeout

  #  Lambda:
  #    Type: AWS::CloudFormation::Stack
  #    DependsOn:
  #      - VPC
  #      - RDS
  #    Properties:
  #      Parameters:
  #        EnvironmentName: !Ref EnvironmentName
  #        DBHost: !GetAtt [ RDS, Outputs.DBInstanceHost ]
  #        DBPort: !GetAtt [ RDS, Outputs.DBInstancePort ]
  #        DBSecurityGroupId: !GetAtt [ RDS, Outputs.DatabaseSG ]
  #        VpcId: !GetAtt [ VPC, Outputs.DatabaseSG ]
  #        VpcSubnetIds:
  #          - !GetAtt [ VPC, Outputs.PrivateSubnet1 ]
  #          - !GetAtt [ VPC, Outputs.PrivateSubnet2 ]
  #      Tags:
  #        - Key: environment
  #          Value: !Ref EnvironmentName
  #      TemplateURL: ./lambda.yaml
  #      TimeoutInMinutes: !Ref StackTimeout

  ECSCluster:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPC
      - RDS
      - ECSRoles
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !Ref VPC
        DBSecurityGroupId: !GetAtt [ RDS, Outputs.DatabaseSG ]
        LoadBalancerSubnets:
          - !GetAtt [ VPC, Outputs.PublicSubnet1 ]
          - !GetAtt [ VPC, Outputs.PublicSubnet2 ]
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ./ecs-cluster.yaml
      TimeoutInMinutes: !Ref StackTimeout


