AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  StackTimeout:
    Default: 10
    Description: A stack timeout in minutes
    Type: String

Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ../stacks/vpc.yaml
      TimeoutInMinutes: !Ref StackTimeout

  ECSRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ../stacks/ecs-roles.yaml
      TimeoutInMinutes: !Ref StackTimeout

  RDS:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcSubnetIds:
          - !GetAtt [ VPC, Outputs.PrivateSubnet1 ]
          - !GetAtt [ VPC, Outputs.PrivateSubnet2 ]
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ../stacks/rds.yaml
      TimeoutInMinutes: !Ref StackTimeout

  ECSCluster:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPC
      - RDS
      - ECSRoles
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !Ref VPC
        DBSecurityGroupId: !GetAtt [ RDS, Outputs.DatabaseSG ]
        LoadBalancerSubnets:
          - !GetAtt [ VPC, Outputs.PublicSubnet1 ]
          - !GetAtt [ VPC, Outputs.PublicSubnet2 ]
      Tags:
        - Key: environment
          Value: !Ref EnvironmentName
      TemplateURL: ../stacks/ecs-cluster.yaml
      TimeoutInMinutes: !Ref StackTimeout


