Transform: AWS::Serverless-2016-10-31
Description: This template deploys

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: 'development'

Resources:

  SetupDatabaseLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: database_setup.lambda_handler
      Runtime: python3.9
      CodeUri: ../lambda/database-setup
      Timeout: 45
      VpcConfig:
        SecurityGroupIds:
          - !Ref SetupDatabaseLambdaSG
        SubnetIds:
          - !ImportValue
            'Fn::Sub': '${EnvironmentName}:PrivateSubnet1'
          - !ImportValue
            'Fn::Sub': '${EnvironmentName}:PrivateSubnet2'
      Environment:
        Variables:
          Environment: !Ref EnvironmentName
          DBUsername: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:username}}'
          DBPassword: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:password}}'
          DBHost: !ImportValue
            'Fn::Sub': '${EnvironmentName}:DBInstanceHost'
          DBPort: !ImportValue
            'Fn::Sub': '${EnvironmentName}:DBInstancePort'

  SetupDatabaseLambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: database-setup-pg-lambda-sg
      GroupDescription: Database setup PostgreSQL lambda SG
      VpcId: !ImportValue
        'Fn::Sub': '${EnvironmentName}:VpcId'

  LambdaToDatabaseIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: TCP
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref SetupDatabaseLambdaSG
      GroupId: !ImportValue
        'Fn::Sub': '${EnvironmentName}:DatabaseSG'

Outputs:
  SetupDatabaseLambda:
    Description: ARN of setup database lambda
    Value: !GetAtt SetupDatabaseLambda.Arn
    Export:
      Name: !Sub ${EnvironmentName}:SetupDatabaseLambda