Transform: AWS::Serverless-2016-10-31
Description: This template deploys

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: 'development'

Resources:

  DatabaseSetupPGLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: database_setup.lambda_handler
      Runtime: python3.9
      CodeUri: ../lambda/database-setup
      Timeout: 45
      VpcConfig:
        SecurityGroupIds:
          - !Ref DatabaseSetupPGLambdaSG
        SubnetIds:
          - !ImportValue
            'Fn::Sub': '${EnvironmentName}:PrivateSubnet1'
          - !ImportValue
            'Fn::Sub': '${EnvironmentName}:PrivateSubnet2'
      Environment:
        Variables:
          Environment: !Ref EnvironmentName
          DBUsername: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:username}}'
          DBPassword: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:password}}'
          DBHost: !ImportValue
            'Fn::Sub': '${EnvironmentName}:DBInstanceHost'
          DBPort: !ImportValue
            'Fn::Sub': '${EnvironmentName}:DBInstancePort'

  DatabaseSetupPGLambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: database-setup-pg-lambda-sg
      GroupDescription: Database setup PostgreSQL lambda SG
      VpcId: !ImportValue
        'Fn::Sub': '${EnvironmentName}:VpcId'

Outputs:
  DatabaseSetupPGLambda:
    Description: ARN of PostgreSQL DB setup lambda function
    Value: !GetAtt DatabaseSetupPGLambda.Arn
    Export:
      Name: !Sub ${EnvironmentName}:DatabaseSetupPGLambda