Description: This template deploys Postgres DB

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: 'development'

Resources:

  DatabaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: service-to-rds-sg
      GroupDescription: Open database for access
      VpcId: !ImportValue
        'Fn::Sub': '${EnvironmentName}:VpcId'
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !ImportValue
            'Fn::Sub': '${EnvironmentName}:ContainerSG'

  DBVpcSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${EnvironmentName}-db-vpc-subnet-group'
      DBSubnetGroupDescription: DB subnet group to connect in private vpc
      SubnetIds:
        - !ImportValue
          'Fn::Sub': '${EnvironmentName}:PrivateSubnet1'
        - !ImportValue
          'Fn::Sub': '${EnvironmentName}:PrivateSubnet2'

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Sub '${EnvironmentName}PocDatabase'
      Engine: postgres
      EngineVersion: 14.2
      MultiAZ: false
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:password}}'
      DBSubnetGroupName: !Ref DBVpcSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DatabaseSG.GroupId

Outputs:
  DBInstance:
    Description: The DB instance ID
    Value: !Ref DBInstance
    Export:
      Name: !Sub ${EnvironmentName}:DBInstance
  DBInstanceHost:
    Description: The DB instance host
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}:DBInstanceHost
  DBInstancePort:
    Description: The DB instance port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${EnvironmentName}:DBInstancePort
