AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys Postgres DB

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  DatabaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: access-rds-sg
      GroupDescription: Open database for access
      VpcId: !Ref VpcId

  DBVpcSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${EnvironmentName}-db-vpc-subnet-group'
      DBSubnetGroupDescription: DB subnet group to connect in private vpc
      SubnetIds: !Ref VpcSubnetIds

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Sub '${EnvironmentName}PocDatabase'
      Engine: postgres
      EngineVersion: 14.2
      MultiAZ: false
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${EnvironmentName}-DBSecret:SecretString:password}}'
      DBSubnetGroupName: !Ref DBVpcSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DatabaseSG.GroupId

Outputs:
  DBInstance:
    Description: The DB instance ID
    Value: !Ref DBInstance
    Export:
      Name: !Sub ${EnvironmentName}:DBInstance
  DBInstanceHost:
    Description: The DB instance host
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}:DBInstanceHost
  DBInstancePort:
    Description: The DB instance port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${EnvironmentName}:DBInstancePort
  DatabaseSG:
    Description: The DB security group
    Value: !Ref DatabaseSG
    Export:
      Name: !Sub ${EnvironmentName}:DatabaseSG
