AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys S3 buckets

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:

  LambdaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${EnvironmentName}-lambda-${AWS::AccountId}
      AccessControl: Private

  CloudformationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${EnvironmentName}-cfn-${AWS::AccountId}
      AccessControl: Private

Outputs:
  LambdaBucket:
    Description: Name of lambda bucket
    Value: !Ref LambdaBucket
    Export:
      Name: !Sub ${EnvironmentName}:LambdaBucket

  CloudformationBucket:
    Description: Name of cloudformation bucket
    Value: !Ref CloudformationBucket
    Export:
      Name: !Sub ${EnvironmentName}:CloudformationBucket