AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys AWS SSl/TLS Certificates

Parameters:
  EnvironmentName:
    Type: String

Resources:

  RDSSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/rds
      Description: "Access keys to Postgres DB. This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "master"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'