AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys AWS SSl/TLS Certificates

Parameters:
  EnvironmentName:
    Type: String

Resources:

  MySecretA:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecretForAppA
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'