AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys S3 buckets
# https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-ecs-service-discovery/

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:

  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Sub ${EnvironmentName}-services-ns
      Vpc: !Ref VpcId

Outputs:

  DiscoveryServiceId:
    Description: Discovery service id
    Value: !Ref ServiceDiscoveryNamespace
    Export:
      Name: !Sub ${EnvironmentName}:ServiceDiscoveryNamespaceId