AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys S3 buckets
# https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-ecs-service-discovery/

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  ServiceDiscoveryNamespaceName:
    Default: services
    Type: String

Resources:

  PrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Sub ${EnvironmentName}-${ServiceDiscoveryNamespaceName}
      Vpc: !Ref VpcId

Outputs:

  ServiceDiscoveryId:
    Description: Service discovery id
    Value: !Ref PrivateNamespace
    Export:
      Name: !Sub ${EnvironmentName}:ServiceDiscoveryNamespaceId

  ServiceDiscoveryNamespaceName:
    Description: Service discovery name
    Value: !Sub ${EnvironmentName}-${ServiceDiscoveryNamespaceName}
    Export:
      Name: !Sub ${EnvironmentName}:ServiceDiscoveryNamespaceName