AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys AWS SSl/TLS Certificates

Parameters:
  EnvironmentName:
    Type: String

Resources:
  GiftLifecycleSourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-gift-lifecycle
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt GiftLifecycleDeadLetterQueue.Arn
        maxReceiveCount: 5

  GiftLifecycleDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-gift-lifecycle-dead-letter

  GiftLifecycleSourceQueueManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GiftLifecycleSourceQueuePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'sqs:SendMessage'
              - 'sqs:ReceiveMessage'
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
            Resource: !GetAtt GiftLifecycleSourceQueue.Arn

Outputs:
  GiftLifecycleSourceQueueName:
    Description: Name of gift lifecycle source queue
    Value: !GetAtt GiftLifecycleSourceQueue.QueueName
    Export:
      Name: !Sub ${EnvironmentName}:GiftLifecycleSourceQueueName

  GiftLifecycleSourceQueueArn:
    Description: ARN of gift lifecycle source queue
    Value: !GetAtt GiftLifecycleSourceQueue.Arn
    Export:
      Name: !Sub ${EnvironmentName}:GiftLifecycleSourceQueueArn

  GiftLifecycleSourceQueueManagedPolicy:
    Description: ARN of gift lifecycle source queue
    Value: !Ref GiftLifecycleSourceQueueManagedPolicy
    Export:
      Name: !Sub ${EnvironmentName}:GiftLifecycleSourceQueueManagedPolicyArn