AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template deploys AWS Cognito user pool
# https://georgemao.medium.com/amazon-cognito-automation-with-cloudformation-is-kind-of-tricky-heres-a-quick-example-65bdc61d39f7

Parameters:
  EnvironmentName:
    Type: String
  AppDomainName:
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      UserPoolName: !Sub ${EnvironmentName}.${AppDomainName}-user-pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:3000
        - !Sub https://${EnvironmentName}.${AppDomainName}-user-pool
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Sub
        - 'auth-${Environment}-${Domain}'
        - Domain: !Select [ 0, !Split [ ".", !Ref AppDomainName ] ]
          Environment: !Ref EnvironmentName

Outputs:
  CognitoApplicationDomainName:
    Value: !Ref UserPoolDomain
    Description: The pool application domain name
    Export:
      Name: !Sub ${EnvironmentName}:CognitoApplicationDomainName
  CognitoUserPoolId:
    Value: !Ref UserPool
    Description: The user pool ID
    Export:
      Name: !Sub ${EnvironmentName}:CognitoUserPoolId
  CognitoClientId:
    Value: !Ref UserPoolClient
    Description: The app client ID
    Export:
      Name: !Sub ${EnvironmentName}:CognitoClientId