name: Delete Infrastructure

on:
  schedule:
    - cron: '*/5 * * * *'

env:
  ENVIRONMENT: development

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - id: delete-stack
        run: |
          aws cloudformation delete-stack \
            --stack-name ${{ env.ENVIRONMENT }}-infrastructure
        shell: bash