name: Deploy Infrastructure

on: workflow_dispatch

env:
  ENVIRONMENT: development
  AWS_REGION: us-east-1

jobs:
  deploy-vpc:
    name: Deploy VPC
    environment: development
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-access-key-id: trewq
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-secret-access-key: trwq
          aws-region: ${{ env.AWS_REGION }}

      - id: deploy-vpc
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Deploy to env ${{ env.ENVIRONMENT }}
          template: stacks/vpc.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"
