name: Deploy Infrastructure

on: workflow_dispatch

env:
  ENVIRONMENT: development
  AWS_REGION: us-east-1

jobs:
  deploy-vpc:
    name: Deploy VPC
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: deploy-vpc
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-vpc
          template: stacks/vpc.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"

  deploy-ecs-roles:
    needs: deploy-vpc
    name: Deploy ECS Roles
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: deploy-ecs-roles
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-ecs-roles
          template: stacks/ecs-roles.yaml
          no-fail-on-empty-changeset: "1"

  deploy-ecs-cluster:
    needs: deploy-ecs-roles
    name: Deploy ECS Cluster
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: deploy-ecs-cluster
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-poc-cluster
          template: stacks/ecs-cluster.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"