name: Deploy Infrastructure

on: workflow_dispatch

env:
  ENVIRONMENT: development
  AWS_REGION: us-east-1

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: deploy-s3
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: ${{ env.ENVIRONMENT }}-s3
          template: stacks/s3.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"

      - id: aws-package-infrastructure-stack
        run: |
          aws cloudformation package \
            --template-file stacks/infrastructure.yaml \
            --output-template-file stacks/infrastructure.packaged.yaml \
            --s3-prefix aws-infra/stacks \
            --s3-bucket ${{ steps.deploy-s3.outputs.CFNTemplatesBucket }}
        shell: bash

      - id: deploy-infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: ${{ env.ENVIRONMENT }}-infrastructure
          template: stacks/infrastructure.packaged.yaml
          no-fail-on-empty-changeset: "1"
          capabilities: 'CAPABILITY_IAM, CAPABILITY_AUTO_EXPAND' # CAPABILITY_AUTO_EXPAND required by lambda, CAPABILITY_IAM - default
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"