name: Deploy Infrastructure

on: workflow_dispatch

env:
  ENVIRONMENT: development
  AWS_REGION: us-east-1

jobs:
  deploy-s3:
    name: Deploy S3 Buckets
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: deploy-s3
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: ${{ env.ENVIRONMENT }}-s3
          template: stacks/s3.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"
      - id: aws-package-lambda-stack
        env:
          CLOUDFORMATION_BUCKET_NAME: ${{ steps.deploy-s3.outputs.CLOUDFORMATION_BUCKET_NAME }}
        run: |
          echo "aws cloudformation package to -> $CLOUDFORMATION_BUCKET_NAME"
        shell: bash
    outputs:
      LAMBDA_BUCKET_NAME: ${{ steps.deploy-s3.outputs.LambdaBucket }}
      CLOUDFORMATION_BUCKET_NAME: ${{ steps.deploy-s3.outputs.CloudformationBucket }}
      stack-id: ${{ steps.deploy-s3.outputs.stack-id }}

  deploy-infrastructure:
    needs:
      - deploy-s3
    name: Deploy infrastructure
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - id: aws-package-lambda-stack
        env:
          CLOUDFORMATION_BUCKET_NAME: ${{ needs.deploy-s3.outputs.CLOUDFORMATION_BUCKET_NAME }}
        run: |
          echo "aws cloudformation package"
          aws cloudformation package \
            --template-file stacks/infrastructure.yaml \
            --output-template-file stacks/infrastructure.packaged.yaml \
            --s3-prefix aws-infra/stacks \
            --s3-bucket $CLOUDFORMATION_BUCKET_NAME
        shell: bash

      - id: deploy-infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-infrastructure
          template: stacks/infrastructure.packaged.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"

  deploy-lambda:
    needs:
      - deploy-infrastructure
      - deploy-s3
    name: Deploy Lambda functions
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - id: aws-package-lambda-stack
        env:
          LAMBDA_BUCKET_NAME: ${{ needs.deploy-s3.outputs.LAMBDA_BUCKET_NAME }}
        run: |
          echo "aws cloudformation package"
          aws cloudformation package \
            --template-file stacks/lambda.yaml \
            --output-template-file stacks/lambda.packaged.yaml \
            --s3-prefix aws-infra/database-setup \
            --s3-bucket $LAMBDA_BUCKET_NAME
        shell: bash
      - id: deploy-lambda
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-lambda
          template: stacks/lambda.packaged.yaml
          capabilities: 'CAPABILITY_IAM, CAPABILITY_AUTO_EXPAND' # required by lambda
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"