name: Deploy Infrastructure

on: workflow_dispatch

env:
  ENVIRONMENT: development
  AWS_REGION: us-east-1

jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: deploy-infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-infrastructure
          template: stacks/infrastructure.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"

  deploy-s3-lambda:
    needs: deploy-infrastructure
    name: Deploy Lambda functions
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - id: aws-package-lambda-stack
        env:
          LAMBDA_BUCKET_NAME: ${{ env.ENVIRONMENT }}-lambda-${{ steps.configure-aws-credentials.outputs.aws-account-id }}
        run: |
          echo "aws cloudformation package"
          aws cloudformation package \
            --template-file stacks/lambda.yaml \
            --output-template-file stacks/lambda.packaged.yaml \
            --s3-prefix aws-infra/database-setup \
            --s3-bucket $LAMBDA_BUCKET_NAME
        shell: bash
      - id: deploy-lambda
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-lambda
          template: stacks/lambda.packaged.yaml
          capabilities: 'CAPABILITY_IAM, CAPABILITY_AUTO_EXPAND' # required by lambda
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "EnvironmentName=${{ env.ENVIRONMENT }}"